# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ware', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=1000)),
                ('cold_total', models.PositiveSmallIntegerField(default=0)),
                ('hot_total', models.PositiveSmallIntegerField(default=0)),
                ('mild_total', models.PositiveSmallIntegerField(default=0)),
                ('severe_total', models.PositiveSmallIntegerField(default=0)),
                ('cold_available', models.PositiveSmallIntegerField(default=0)),
                ('hot_available', models.PositiveSmallIntegerField(default=0)),
                ('mild_available', models.PositiveSmallIntegerField(default=0)),
                ('severe_available', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
