# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ware', '0002_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='cold_available',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='cold_total',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='hot_available',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='hot_total',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='mild_available',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='mild_total',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='severe_available',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='severe_total',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
