# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ware', '0004_auto_20160717_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ware_owner', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('quantity', models.PositiveSmallIntegerField(default=0, null=True)),
                ('type_of', models.CharField(max_length=100)),
                ('price', models.PositiveSmallIntegerField(default=0, null=True)),
            ],
        ),
    ]
